# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='encoded_image',
            field=models.CharField(default='a', max_length=10000),
            preserve_default=False,
        ),
    ]
