# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-26 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20161226_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AlterField(
            model_name='post',
            name='encoded_image',
            field=models.TextField(),
        ),
    ]
